// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Web.Models
{
    public partial class Administrator
    {
        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Column("username")]
        [StringLength(30)]
        public string Username { get; set; }
        [Column("password")]
        [StringLength(30)]
        public string Password { get; set; }
    }
}