// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;

namespace Web.Models
{

    public partial class CartItem
    {
        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Column("orderId", TypeName = "int(11)")]
        public int OrderId { get; set; }
        [Column("productId", TypeName = "int(11)")]
        public int ProductId { get; set; }
        [Column("quantity", TypeName = "int(11)")]
        public int Quantity { get; set; } =1;
        [Required]
        [Column("size")]
        [StringLength(2)]
        public string Size { get; set; }
        [Required]
        [Column("color")]
        [StringLength(20)]
        public string Color { get; set; }

        [ForeignKey("OrderId")]
        [InverseProperty("CartItems")]
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
        public int TotalPrice { get; set; }

        public void QtityChange(int value)
        {
            
            if (value == 0)
            {
                this.Quantity += 1;
                this.TotalPrice = this.Product.Price * Quantity;
            }else if (value == 1 && this.Quantity >1)
            {
                this.Quantity -= 1;
                this.TotalPrice = this.Product.Price * Quantity;
            }
        }

    }
}