// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Web.Models
{

    public partial class Photo
    {
        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Column("productId", TypeName = "int(11)")]
        public int? ProductId { get; set; }
        [Column("imgPath")]
        [StringLength(300)]
        public string ImgPath { get; set; }
        [Column("priority", TypeName = "int(1)")]
        public int Priority { get; set; }

        [ForeignKey("ProductId")]
        [InverseProperty("Photos")]
        public virtual Product Product { get; set; }
    }
}