// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Web.Models
{
    public partial class Product
    {
        public Product()
        {
            Photos = new HashSet<Photo>();
        }

        [Key]
        [Column("id", TypeName = "int(11)")]
        public int Id { get; set; }
        [Column("productName")]
        [StringLength(50)]
        public string ProductName { get; set; }
        [Column("productDetailName")]
        [StringLength(50)]
        public string ProductDetailName { get; set; }
        [Column("price")]
        [Precision(10, 0)]
        public int Price { get; set; }
        [Column("oldPrice")]
        [Precision(10, 0)]
        public int OldPrice { get; set; }
        [Column("infoText")]
        [StringLength(500)]
        public string InfoText { get; set; }
        [Column("infoText2")]
        [StringLength(1000)]
        public string InfoText2 { get; set; }
        [Column("type")]
        [StringLength(50)]
        public string Type { get; set; }
        [Column("material")]
        [StringLength(50)]
        public string Material { get; set; }
        [Column("sex", TypeName = "int(1)")]
        public int? Sex { get; set; }
        [Column("productCode")]
        [StringLength(50)]
        public string ProductCode { get; set; }

        [InverseProperty("Product")]
        public virtual ICollection<Photo> Photos { get; set; }
        

        public Photo MainPhoto()
        {
            return this.Photos.Where(x => x.Priority == 1).FirstOrDefault();
        }
    }
}